version: "3"

services:
  nginx:
    build: ./config/nginx
    container_name: onspace-nginx
    depends_on:
      - web
    links:
      - web:web
    networks:
      - onspace
    ports:
      - 8000:8000
    restart: unless-stopped
  
networks:
  onspace:
    driver: bridge